<?php

namespace ContainerRWbhxvk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QkwI26cService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qkwI26c' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qkwI26c'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'twoFactor' => ['services', 'scheb_two_factor.security.google_authenticator', 'getSchebTwoFactor_Security_GoogleAuthenticatorService', true],
        ], [
            'twoFactor' => '?',
        ]);
    }
}
