<?php

namespace ContainerRWbhxvk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WpOc8YhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wpOc8Yh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wpOc8Yh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Pimcore\\Http\\Request\\Resolver\\DocumentResolver' => ['services', 'Pimcore\\Http\\Request\\Resolver\\DocumentResolver', 'getDocumentResolverService', false],
            'Pimcore\\Http\\Request\\Resolver\\EditmodeResolver' => ['services', 'Pimcore\\Http\\Request\\Resolver\\EditmodeResolver', 'getEditmodeResolverService', false],
            'Pimcore\\Http\\Request\\Resolver\\ResponseHeaderResolver' => ['services', 'Pimcore\\Http\\Request\\Resolver\\ResponseHeaderResolver', 'getResponseHeaderResolverService', false],
            'Pimcore\\Templating\\Renderer\\EditableRenderer' => ['services', 'Pimcore\\Templating\\Renderer\\EditableRenderer', 'getEditableRendererService', false],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'form.factory' => ['services', '.container.private.form.factory', 'get_Container_Private_Form_FactoryService', false],
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
            'pimcore.templating' => ['services', 'pimcore.templating.engine.delegating', 'getPimcore_Templating_Engine_DelegatingService', false],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'router' => ['services', 'router', 'getRouterService', false],
            'security.authorization_checker' => ['services', 'security.authorization_checker', 'getSecurity_AuthorizationCheckerService', false],
            'security.csrf.token_manager' => ['services', '.container.private.security.csrf.token_manager', 'get_Container_Private_Security_Csrf_TokenManagerService', true],
            'security.token_storage' => ['services', 'security.token_storage', 'getSecurity_TokenStorageService', false],
            'serializer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', true],
            'session' => ['services', 'session', 'getSessionService', true],
            'twig' => ['services', '.container.private.twig', 'get_Container_Private_TwigService', false],
        ], [
            'Pimcore\\Http\\Request\\Resolver\\DocumentResolver' => 'Pimcore\\Http\\Request\\Resolver\\DocumentResolver',
            'Pimcore\\Http\\Request\\Resolver\\EditmodeResolver' => 'Pimcore\\Http\\Request\\Resolver\\EditmodeResolver',
            'Pimcore\\Http\\Request\\Resolver\\ResponseHeaderResolver' => 'Pimcore\\Http\\Request\\Resolver\\ResponseHeaderResolver',
            'Pimcore\\Templating\\Renderer\\EditableRenderer' => 'Pimcore\\Templating\\Renderer\\EditableRenderer',
            'doctrine' => '?',
            'form.factory' => '?',
            'http_kernel' => '?',
            'parameter_bag' => '?',
            'pimcore.templating' => '?',
            'request_stack' => '?',
            'router' => '?',
            'security.authorization_checker' => '?',
            'security.csrf.token_manager' => '?',
            'security.token_storage' => '?',
            'serializer' => '?',
            'session' => '?',
            'twig' => '?',
        ]);
    }
}
