<?php

namespace ContainerRWbhxvk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEditmodeValueResolverService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'debug.Pimcore\Controller\ArgumentValueResolver\EditmodeValueResolver' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/TraceableValueResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Controller/ArgumentValueResolver/EditmodeValueResolver.php';

        return $container->privates['debug.Pimcore\\Controller\\ArgumentValueResolver\\EditmodeValueResolver'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Pimcore\Controller\ArgumentValueResolver\EditmodeValueResolver(($container->services['Pimcore\\Http\\Request\\Resolver\\EditmodeResolver'] ?? $container->getEditmodeResolverService())), ($container->privates['debug.stopwatch'] ?? ($container->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
    }
}
