<?php

namespace ContainerRWbhxvk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Logout_Listener_LegacySuccessListener_PimcoreAdminService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'security.logout.listener.legacy_success_listener.pimcore_admin' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Security\LegacyLogoutHandlerListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/symfony/src/Symfony/Bundle/SecurityBundle/Security/LegacyLogoutHandlerListener.php';

        return $container->privates['security.logout.listener.legacy_success_listener.pimcore_admin'] = new \Symfony\Bundle\SecurityBundle\Security\LegacyLogoutHandlerListener(($container->services['pimcore_admin.security.logout_success_handler'] ?? $container->load('getPimcoreAdmin_Security_LogoutSuccessHandlerService')));
    }
}
