<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX4LZcJf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX4LZcJf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX4LZcJf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX4LZcJf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX4LZcJf\App_KernelDevDebugContainer([
    'container.build_hash' => 'X4LZcJf',
    'container.build_id' => '6a00df5c',
    'container.build_time' => 1625003153,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX4LZcJf');
