<?php

namespace Container4S0QPlK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ReQ1jVtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.reQ1jVt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.reQ1jVt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'localeService' => ['services', 'Pimcore\\Localization\\LocaleServiceInterface', 'getLocaleServiceInterfaceService', true],
        ], [
            'localeService' => 'Pimcore\\Localization\\LocaleServiceInterface',
        ]);
    }
}
