<?php

namespace Container4S0QPlK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGeopolygonService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Pimcore\DataObject\BlockDataMarshaller\Geopolygon' shared autowired service.
     *
     * @return \Pimcore\DataObject\BlockDataMarshaller\Geopolygon
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Marshaller/MarshallerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/DataObject/BlockDataMarshaller/Geopolygon.php';

        return $container->services['Pimcore\\DataObject\\BlockDataMarshaller\\Geopolygon'] = new \Pimcore\DataObject\BlockDataMarshaller\Geopolygon();
    }
}
