<?php

namespace Container4S0QPlK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMiscControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Pimcore\Bundle\AdminBundle\Controller\Admin\MiscController' shared autowired service.
     *
     * @return \Pimcore\Bundle\AdminBundle\Controller\Admin\MiscController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Controller/Controller.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/DoubleAuthenticationControllerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/AdminControllerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/AdminController.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/MiscController.php';

        $container->services['Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\MiscController'] = $instance = new \Pimcore\Bundle\AdminBundle\Controller\Admin\MiscController();

        $instance->setContainer(($container->privates['.service_locator..bScqu9'] ?? $container->load('get_ServiceLocator__BScqu9Service'))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\MiscController', $container));

        return $instance;
    }
}
