<?php

namespace Container4S0QPlK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTimestampService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Templating\Helper\Timestamp' shared autowired service.
     *
     * @return \App\Templating\Helper\Timestamp
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Templating\\Helper\\Timestamp'] = new \App\Templating\Helper\Timestamp();
    }
}
