<?php

namespace ContainerX4LZcJf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F_YVVKoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.F.YVVKo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.F.YVVKo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'profiler' => ['services', 'profiler', 'getProfilerService', false],
        ], [
            'profiler' => '?',
        ]);
    }
}
