<?php

namespace ContainerX4LZcJf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NVkq5BvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nVkq5Bv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nVkq5Bv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'treeHelper' => ['privates', 'Pimcore\\Bundle\\PerspectiveEditorBundle\\Services\\TreeHelper', 'getTreeHelperService', true],
            'viewAccessor' => ['privates', 'Pimcore\\Bundle\\PerspectiveEditorBundle\\Services\\ViewAccessor', 'getViewAccessorService', true],
        ], [
            'treeHelper' => 'Pimcore\\Bundle\\PerspectiveEditorBundle\\Services\\TreeHelper',
            'viewAccessor' => 'Pimcore\\Bundle\\PerspectiveEditorBundle\\Services\\ViewAccessor',
        ]);
    }
}
