<?php

namespace ContainerX4LZcJf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G3P4ECDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.g3P4ECD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.g3P4ECD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'conversionService' => ['services', 'Pimcore\\Model\\DataObject\\QuantityValue\\UnitConversionService', 'getUnitConversionServiceService', true],
        ], [
            'conversionService' => 'Pimcore\\Model\\DataObject\\QuantityValue\\UnitConversionService',
        ]);
    }
}
