<?php

namespace ContainerX4LZcJf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInstallerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Pimcore\Bundle\NumberSequenceGeneratorBundle\Installer' shared autowired service.
     *
     * @return \Pimcore\Bundle\NumberSequenceGeneratorBundle\Installer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Extension/Bundle/Installer/InstallerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Extension/Bundle/Installer/AbstractInstaller.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/number-sequence-generator/src/Installer.php';

        return $container->services['Pimcore\\Bundle\\NumberSequenceGeneratorBundle\\Installer'] = new \Pimcore\Bundle\NumberSequenceGeneratorBundle\Installer();
    }
}
