<?php

namespace ContainerX4LZcJf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Pimcore\Mail\Mailer' shared autowired service.
     *
     * @return \Pimcore\Mail\Mailer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/symfony/src/Symfony/Component/Mailer/MailerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Mail/Mailer.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/symfony/src/Symfony/Component/Mailer/Mailer.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/symfony/src/Symfony/Component/Mailer/Transport/TransportInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/symfony/src/Symfony/Component/Mailer/Transport/Transports.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/symfony/src/Symfony/Component/Mailer/Transport.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Mail/Plugins/RedirectingPlugin.php';

        return $container->services['Pimcore\\Mail\\Mailer'] = new \Pimcore\Mail\Mailer(new \Symfony\Component\Mailer\Mailer((new \Symfony\Component\Mailer\Transport(new RewindableGenerator(function () use ($container) {
            yield 0 => $container->load('getMailer_TransportFactory_NullService');
            yield 1 => $container->load('getMailer_TransportFactory_SendmailService');
            yield 2 => $container->load('getMailer_TransportFactory_NativeService');
            yield 3 => $container->load('getMailer_TransportFactory_SmtpService');
        }, 4)))->fromStrings(['main' => 'native://default', 'pimcore_newsletter' => 'native://default']), NULL, ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService())), new \Pimcore\Mail\Plugins\RedirectingPlugin());
    }
}
