<?php

namespace ContainerX4LZcJf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPerspectiveAccessorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Bundle\PerspectiveEditorBundle\Services\PerspectiveAccessor' shared autowired service.
     *
     * @return \Pimcore\Bundle\PerspectiveEditorBundle\Services\PerspectiveAccessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/perspective-editor/src/Services/AbstractAccessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/perspective-editor/src/Services/PerspectiveAccessor.php';

        return $container->privates['Pimcore\\Bundle\\PerspectiveEditorBundle\\Services\\PerspectiveAccessor'] = new \Pimcore\Bundle\PerspectiveEditorBundle\Services\PerspectiveAccessor((\dirname(__DIR__, 4).'/config/pimcore/'));
    }
}
