<?php

namespace ContainerX4LZcJf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSearchControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Pimcore\Bundle\AdminBundle\Controller\Searchadmin\SearchController' shared autowired service.
     *
     * @return \Pimcore\Bundle\AdminBundle\Controller\Searchadmin\SearchController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Controller/Controller.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/DoubleAuthenticationControllerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/AdminControllerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/AdminController.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Searchadmin/SearchController.php';

        $container->services['Pimcore\\Bundle\\AdminBundle\\Controller\\Searchadmin\\SearchController'] = $instance = new \Pimcore\Bundle\AdminBundle\Controller\Searchadmin\SearchController();

        $instance->setContainer(($container->privates['.service_locator.za.1Wif'] ?? $container->load('get_ServiceLocator_Za_1WifService'))->withContext('Pimcore\\Bundle\\AdminBundle\\Controller\\Searchadmin\\SearchController', $container));

        return $instance;
    }
}
