<?php

namespace ContainerX4LZcJf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTreeHelperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Bundle\PerspectiveEditorBundle\Services\TreeHelper' shared autowired service.
     *
     * @return \Pimcore\Bundle\PerspectiveEditorBundle\Services\TreeHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/perspective-editor/src/Services/TreeHelper.php';

        return $container->privates['Pimcore\\Bundle\\PerspectiveEditorBundle\\Services\\TreeHelper'] = new \Pimcore\Bundle\PerspectiveEditorBundle\Services\TreeHelper();
    }
}
