<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.7OiX3ws' shared service.

return $this->privates['.service_locator.7OiX3ws'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'config' => ['services', 'Pimcore\\Config', 'getConfigService', false],
    'csrfProtectionListener' => ['services', 'Pimcore\\Bundle\\AdminBundle\\EventListener\\CsrfProtectionListener', 'getCsrfProtectionListenerService', false],
    'kernel' => ['services', 'kernel', 'getKernelService', false],
    'maintenanceExecutor' => ['privates', 'Pimcore\\Maintenance\\Executor', 'getExecutorService.php', true],
    'siteConfigProvider' => ['privates', 'Pimcore\\Analytics\\Google\\Config\\SiteConfigProvider', 'getSiteConfigProviderService.php', true],
], [
    'config' => 'Pimcore\\Config',
    'csrfProtectionListener' => 'Pimcore\\Bundle\\AdminBundle\\EventListener\\CsrfProtectionListener',
    'kernel' => '?',
    'maintenanceExecutor' => 'Pimcore\\Maintenance\\Executor',
    'siteConfigProvider' => 'Pimcore\\Analytics\\Google\\Config\\SiteConfigProvider',
]);
