<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.BlHxx1B' shared service.

return $this->privates['.service_locator.BlHxx1B'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'workflowManager' => ['services', 'Pimcore\\Workflow\\Manager', 'getManagerService.php', true],
], [
    'workflowManager' => 'Pimcore\\Workflow\\Manager',
]);
