<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.PZLB2ER' shared service.

return $this->privates['.service_locator.PZLB2ER'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'exportService' => ['privates', 'Pimcore\\Translation\\ExportService\\ExportServiceInterface', 'getExportServiceInterfaceService.php', true],
], [
    'exportService' => 'Pimcore\\Translation\\ExportService\\ExportServiceInterface',
]);
