<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.IukZmxB' shared service.

return $this->privates['.service_locator.IukZmxB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'event' => ['privates', '.errored..service_locator.IukZmxB.Symfony\\Component\\HttpKernel\\Event\\FilterResponseEvent', NULL, 'Cannot autowire service ".service_locator.IukZmxB": it references class "Symfony\\Component\\HttpKernel\\Event\\FilterResponseEvent" but no such service exists.'],
], [
    'event' => 'Symfony\\Component\\HttpKernel\\Event\\FilterResponseEvent',
]);
