<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.79sNj_P' shared service.

return $this->privates['.service_locator.79sNj_P'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'redirectHandler' => ['privates', 'Pimcore\\Routing\\RedirectHandler', 'getRedirectHandlerService', false],
], [
    'redirectHandler' => 'Pimcore\\Routing\\RedirectHandler',
]);
