<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.mVxxlcI' shared service.

return $this->privates['.service_locator.mVxxlcI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'widgetBroker' => ['privates', 'Pimcore\\Analytics\\Piwik\\WidgetBroker', 'getWidgetBrokerService.php', true],
], [
    'widgetBroker' => 'Pimcore\\Analytics\\Piwik\\WidgetBroker',
]);
