<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ARfi65E' shared service.

return $this->privates['.service_locator.ARfi65E'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'localeService' => ['services', 'Pimcore\\Localization\\LocaleServiceInterface', 'getLocaleServiceInterfaceService.php', true],
], [
    'localeService' => 'Pimcore\\Localization\\LocaleServiceInterface',
]);
