<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Iwgkd5J' shared service.

return $this->privates['.service_locator.Iwgkd5J'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'siteConfigProvider' => ['privates', 'Pimcore\\Analytics\\SiteId\\SiteIdProvider', 'getSiteIdProviderService', false],
    'sitesManager' => ['privates', 'Pimcore\\Analytics\\Piwik\\Api\\SitesManager', 'getSitesManagerService.php', true],
], [
    'siteConfigProvider' => 'Pimcore\\Analytics\\SiteId\\SiteIdProvider',
    'sitesManager' => 'Pimcore\\Analytics\\Piwik\\Api\\SitesManager',
]);
