<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.vYrMeb.' shared service.

return $this->privates['.service_locator.vYrMeb.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'bruteforceProtectionHandler' => ['services', 'pimcore_admin.security.bruteforce_protection_handler', 'getPimcoreAdmin_Security_BruteforceProtectionHandlerService', false],
    'config' => ['services', 'Pimcore\\Config', 'getConfigService', false],
], [
    'bruteforceProtectionHandler' => '?',
    'config' => 'Pimcore\\Config',
]);
