<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.nt_0e9q' shared service.

return $this->privates['.service_locator.nt_0e9q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'importService' => ['privates', 'Pimcore\\DataObject\\Import\\Service', 'getService4Service.php', true],
], [
    'importService' => 'Pimcore\\DataObject\\Import\\Service',
]);
