<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.12kg0VE' shared service.

return $this->privates['.service_locator.12kg0VE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'assetsInstaller' => ['services', 'Pimcore\\Tool\\AssetsInstaller', 'getAssetsInstallerService.php', true],
    'cacheClearer' => ['services', 'Pimcore\\Cache\\Symfony\\CacheClearer', 'getCacheClearerService.php', true],
    'kernel' => ['services', 'kernel', 'getKernelService', false],
], [
    'assetsInstaller' => 'Pimcore\\Tool\\AssetsInstaller',
    'cacheClearer' => 'Pimcore\\Cache\\Symfony\\CacheClearer',
    'kernel' => '?',
]);
