<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Navigation\Renderer\Breadcrumbs' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Navigation/Renderer/RendererInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Navigation/Renderer/AbstractRenderer.php';
include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Navigation/Renderer/Breadcrumbs.php';

return $this->privates['Pimcore\\Navigation\\Renderer\\Breadcrumbs'] = new \Pimcore\Navigation\Renderer\Breadcrumbs(($this->services['templating'] ?? $this->load('getTemplatingService.php')));
