<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\Model\DataObject\ClassDefinition\ClassDefinitionManager' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Model/DataObject/ClassDefinition/ClassDefinitionManager.php';

return $this->services['Pimcore\\Model\\DataObject\\ClassDefinition\\ClassDefinitionManager'] = new \Pimcore\Model\DataObject\ClassDefinition\ClassDefinitionManager();
