<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Bundle\CoreBundle\Command\ClassesRebuildCommand' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php';
include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Console/AbstractCommand.php';
include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/CoreBundle/Command/ClassesRebuildCommand.php';
include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Model/DataObject/ClassDefinition/ClassDefinitionManager.php';

$this->privates['Pimcore\\Bundle\\CoreBundle\\Command\\ClassesRebuildCommand'] = $instance = new \Pimcore\Bundle\CoreBundle\Command\ClassesRebuildCommand();

$instance->setClassDefinitionManager(($this->services['Pimcore\\Model\\DataObject\\ClassDefinition\\ClassDefinitionManager'] ?? ($this->services['Pimcore\\Model\\DataObject\\ClassDefinition\\ClassDefinitionManager'] = new \Pimcore\Model\DataObject\ClassDefinition\ClassDefinitionManager())));
$instance->setName('pimcore:deployment:classes-rebuild');

return $instance;
