<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Templating\HelperBroker\DocumentEditable' shared autowired service.

@trigger_error('The "Pimcore\\Templating\\HelperBroker\\DocumentEditable" service is deprecated and will be removed in Pimcore 7', E_USER_DEPRECATED);

return new \Pimcore\Templating\HelperBroker\DocumentEditable(($this->services['Pimcore\\Templating\\Renderer\\EditableRenderer'] ?? $this->load('getEditableRendererService.php')));
