<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\Document\Editable\EditableUsageResolver' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Document/Editable/EditableUsageResolver.php';

return $this->services['Pimcore\\Document\\Editable\\EditableUsageResolver'] = new \Pimcore\Document\Editable\EditableUsageResolver(($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->services['Pimcore\\Document\\Renderer\\DocumentRenderer'] ?? $this->load('getDocumentRendererService.php')));
