<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\Templating\Renderer\EditableRenderer' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Templating/Renderer/EditableRenderer.php';

$this->services['Pimcore\\Templating\\Renderer\\EditableRenderer'] = $instance = new \Pimcore\Templating\Renderer\EditableRenderer(($this->services['Pimcore\\Model\\Document\\Editable\\Loader\\EditableLoader'] ?? $this->load('getEditableLoaderService.php')), ($this->services['Pimcore\\Http\\Request\\Resolver\\EditmodeResolver'] ?? $this->getEditmodeResolverService()));

$a = ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService());

$instance->setLogger($a);
$instance->setLogger($a);

return $instance;
