<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.l1CuC14.Symfony\Component\HttpKernel\Event\FilterControllerEvent' shared service.

$this->throw('Cannot autowire service ".service_locator.l1CuC14": it references class "Symfony\\Component\\HttpKernel\\Event\\FilterControllerEvent" but no such service exists.');
