<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.AfmubPA.Pimcore\Event\Webservice\FilterEvent' shared service.

$this->throw('Cannot autowire service ".service_locator.AfmubPA": it references class "Pimcore\\Event\\Webservice\\FilterEvent" but no such service exists.');
