<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\Workflow\Dumper\GraphvizDumper' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/symfony/src/Symfony/Component/Workflow/Dumper/DumperInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Workflow/Dumper/GraphvizDumper.php';

return $this->services['Pimcore\\Workflow\\Dumper\\GraphvizDumper'] = new \Pimcore\Workflow\Dumper\GraphvizDumper(($this->services['Pimcore\\Workflow\\Manager'] ?? $this->load('getManagerService.php')));
