<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Targeting\DataProvider\GeoIp' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Targeting/DataProvider/DataProviderInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Targeting/DataProvider/GeoIp.php';
include_once \dirname(__DIR__, 4).'/vendor/geoip2/geoip2/src/ProviderInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/geoip2/geoip2/src/Database/Reader.php';

$this->privates['Pimcore\\Targeting\\DataProvider\\GeoIp'] = $instance = new \Pimcore\Targeting\DataProvider\GeoIp(new \GeoIp2\Database\Reader(NULL), ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()));

$instance->setCache(($this->services['pimcore.cache.core.handler'] ?? $this->getPimcore_Cache_Core_HandlerService()));

return $instance;
