<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'presta_sitemap.controller' shared service.

include_once \dirname(__DIR__, 4).'/vendor/presta/sitemap-bundle/Controller/SitemapController.php';

return $this->services['presta_sitemap.controller'] = new \Presta\SitemapBundle\Controller\SitemapController(($this->services['presta_sitemap.generator'] ?? $this->load('getPrestaSitemap_GeneratorService.php')), 3600);
