<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'pimcore.model.factory' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Loader/ImplementationLoader/LoaderInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Loader/ImplementationLoader/ClassNameLoaderInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Loader/ImplementationLoader/ImplementationLoader.php';
include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Model/FactoryInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Model/Factory.php';
include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Loader/ImplementationLoader/AbstractClassNameLoader.php';
include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Model/Factory/FallbackBuilder.php';
include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Loader/ImplementationLoader/ClassMapLoader.php';

$this->services['pimcore.model.factory'] = $instance = new \Pimcore\Model\Factory();

$instance->addLoader(new \Pimcore\Model\Factory\FallbackBuilder());
$instance->addLoader(new \Pimcore\Loader\ImplementationLoader\ClassMapLoader([]));

return $instance;
