<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'pimcore.twig.extension.templating_helper' shared autowired service.

@trigger_error('The "pimcore.twig.extension.templating_helper" service is deprecated.', E_USER_DEPRECATED);

return $this->services['pimcore.twig.extension.templating_helper'] = new \Pimcore\Twig\Extension\TemplatingHelperExtension(($this->services['pimcore.templating.engine.php'] ?? $this->load('getPimcore_Templating_Engine_PhpService.php')));
