<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'pimcore.workflow.place-options-provider' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/DynamicOptionsProvider/MultiSelectOptionsProviderInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/DynamicOptionsProvider/SelectOptionsProviderInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Workflow/Place/OptionsProvider.php';

return $this->services['pimcore.workflow.place-options-provider'] = new \Pimcore\Workflow\Place\OptionsProvider(($this->services['Pimcore\\Workflow\\Manager'] ?? $this->load('getManagerService.php')), ($this->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? $this->getTranslatorInterfaceService()));
