<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pimcore.security.encoder_factory' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Encoder/EncoderFactoryInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Security/Encoder/EncoderFactory.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Encoder/EncoderFactory.php';
include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Security/Encoder/Factory/AbstractEncoderFactory.php';
include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Security/Encoder/Factory/UserAwareEncoderFactory.php';

return $this->privates['pimcore.security.encoder_factory'] = new \Pimcore\Security\Encoder\EncoderFactory(new \Symfony\Component\Security\Core\Encoder\EncoderFactory([]), ['Pimcore\\Bundle\\AdminBundle\\Security\\User\\User' => new \Pimcore\Security\Encoder\Factory\UserAwareEncoderFactory('Pimcore\\Bundle\\AdminBundle\\Security\\Encoder\\AdminPasswordEncoder')]);
