<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pimcore.data_object.import.operator.factory.object_brick_setter' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/DataObject/Import/ColumnConfig/Operator/Factory/OperatorFactoryInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/DataObject/Import/ColumnConfig/Operator/Factory/ObjectBrickSetterFactory.php';

return $this->privates['pimcore.data_object.import.operator.factory.object_brick_setter'] = new \Pimcore\DataObject\Import\ColumnConfig\Operator\Factory\ObjectBrickSetterFactory(($this->services['pimcore.model.factory'] ?? $this->load('getPimcore_Model_FactoryService.php')));
