<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'pimcore.templating.include_renderer' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Templating/Renderer/IncludeRenderer.php';

return $this->services['pimcore.templating.include_renderer'] = new \Pimcore\Templating\Renderer\IncludeRenderer(($this->services['pimcore.templating.action_renderer'] ?? $this->load('getPimcore_Templating_ActionRendererService.php')), ($this->services['Pimcore\\Targeting\\Document\\DocumentTargetingConfigurator'] ?? $this->getDocumentTargetingConfiguratorService()));
