<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'pimcore.templating.action_renderer' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Templating/Renderer/ActionRenderer.php';

return $this->services['pimcore.templating.action_renderer'] = new \Pimcore\Templating\Renderer\ActionRenderer(($this->privates['templating.helper.actions'] ?? $this->load('getTemplating_Helper_ActionsService.php')), ($this->services['pimcore.controller.config.config_normalizer'] ?? $this->getPimcore_Controller_Config_ConfigNormalizerService()));
