<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'pimcore_admin.security.logout_success_handler' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Logout/LogoutSuccessHandlerInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/AdminBundle/Security/LogoutSuccessHandler.php';

$this->services['pimcore_admin.security.logout_success_handler'] = $instance = new \Pimcore\Bundle\AdminBundle\Security\LogoutSuccessHandler(($this->services['security.token_storage'] ?? $this->getSecurity_TokenStorageService()), ($this->services['router'] ?? $this->getRouterService()), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));

$a = ($this->services['monolog.logger.security'] ?? $this->getMonolog_Logger_SecurityService());

$instance->setLogger($a);
$instance->setLogger($a);

return $instance;
