<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Config\ReportConfigWriter' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Config/ReportConfigWriter.php';

return $this->privates['Pimcore\\Config\\ReportConfigWriter'] = new \Pimcore\Config\ReportConfigWriter(($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));
