<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Analytics\Piwik\Api\SitesManager' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Analytics/Piwik/Api/SitesManager.php';

return $this->privates['Pimcore\\Analytics\\Piwik\\Api\\SitesManager'] = new \Pimcore\Analytics\Piwik\Api\SitesManager(($this->privates['Pimcore\\Analytics\\Piwik\\Config\\ConfigProvider'] ?? ($this->privates['Pimcore\\Analytics\\Piwik\\Config\\ConfigProvider'] = new \Pimcore\Analytics\Piwik\Config\ConfigProvider())), ($this->privates['Pimcore\\Analytics\\Piwik\\Api\\ApiClient'] ?? $this->load('getApiClientService.php')), ($this->privates['Pimcore\\Config\\ReportConfigWriter'] ?? $this->load('getReportConfigWriterService.php')), ($this->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? $this->getTranslatorInterfaceService()), ($this->services['Pimcore\\Config'] ?? ($this->services['Pimcore\\Config'] = new \Pimcore\Config())));
