<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'scheb_two_factor.authenticated_token_handler' shared service.

if ($lazyLoad) {
    return $this->privates['scheb_two_factor.authenticated_token_handler'] = $this->createProxy('AuthenticatedTokenHandler_e3677d3', function () {
        return \AuthenticatedTokenHandler_e3677d3::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) {
            $wrappedInstance = $this->load('getSchebTwoFactor_AuthenticatedTokenHandlerService.php', false);

            $proxy->setProxyInitializer(null);

            return true;
        });
    });
}

include_once \dirname(__DIR__, 4).'/vendor/scheb/two-factor-bundle/Security/TwoFactor/Handler/AuthenticationHandlerInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/scheb/two-factor-bundle/Security/TwoFactor/Handler/AuthenticatedTokenHandler.php';

return new \Scheb\TwoFactorBundle\Security\TwoFactor\Handler\AuthenticatedTokenHandler(($this->privates['scheb_two_factor.ip_whitelist_handler'] ?? $this->load('getSchebTwoFactor_IpWhitelistHandlerService.php')), $this->parameters['scheb_two_factor.security_tokens']);
