<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Analytics\Google\Config\SiteConfigProvider' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Analytics/Google/Config/SiteConfigProvider.php';

return $this->privates['Pimcore\\Analytics\\Google\\Config\\SiteConfigProvider'] = new \Pimcore\Analytics\Google\Config\SiteConfigProvider(($this->privates['Pimcore\\Analytics\\SiteId\\SiteIdProvider'] ?? $this->getSiteIdProviderService()), ($this->privates['Pimcore\\Analytics\\Google\\Config\\ConfigProvider'] ?? ($this->privates['Pimcore\\Analytics\\Google\\Config\\ConfigProvider'] = new \Pimcore\Analytics\Google\Config\ConfigProvider())));
