<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\DataObject\Import\Service' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/DataObject/Import/Service.php';

return $this->privates['Pimcore\\DataObject\\Import\\Service'] = new \Pimcore\DataObject\Import\Service(($this->services['doctrine.dbal.default_connection'] ?? $this->getDoctrine_Dbal_DefaultConnectionService()), new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'code' => ['privates', 'Pimcore\\DataObject\\Import\\Resolver\\Code', 'getCodeService.php', true],
    'filename' => ['privates', 'Pimcore\\DataObject\\Import\\Resolver\\Filename', 'getFilenameService.php', true],
    'fullpath' => ['privates', 'Pimcore\\DataObject\\Import\\Resolver\\Fullpath', 'getFullpathService.php', true],
    'getBy' => ['privates', 'Pimcore\\DataObject\\Import\\Resolver\\GetBy', 'getGetByService.php', true],
    'id' => ['privates', 'Pimcore\\DataObject\\Import\\Resolver\\Id', 'getIdService.php', true],
], [
    'code' => '?',
    'filename' => '?',
    'fullpath' => '?',
    'getBy' => '?',
    'id' => '?',
]), new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'Base64' => ['privates', 'pimcore.data_object.import.operator.factory.base64', 'getPimcore_DataObject_Import_Operator_Factory_Base64Service.php', true],
    'Iterator' => ['privates', 'pimcore.data_object.import.operator.factory.iterator', 'getPimcore_DataObject_Import_Operator_Factory_IteratorService.php', true],
    'LocaleSwitcher' => ['privates', 'pimcore.data_object.import.operator.factory.locale_switcher', 'getPimcore_DataObject_Import_Operator_Factory_LocaleSwitcherService.php', true],
    'ObjectBrickSetter' => ['privates', 'pimcore.data_object.import.operator.factory.object_brick_setter', 'getPimcore_DataObject_Import_Operator_Factory_ObjectBrickSetterService.php', true],
    'PHPCode' => ['privates', 'pimcore.data_object.import.operator.factory.php_code', 'getPimcore_DataObject_Import_Operator_Factory_PhpCodeService.php', true],
    'Published' => ['privates', 'pimcore.data_object.import.operator.factory.published', 'getPimcore_DataObject_Import_Operator_Factory_PublishedService.php', true],
    'Splitter' => ['privates', 'pimcore.data_object.import.operator.factory.splitter', 'getPimcore_DataObject_Import_Operator_Factory_SplitterService.php', true],
    'Unserialize' => ['privates', 'pimcore.data_object.import.operator.factory.unserialize', 'getPimcore_DataObject_Import_Operator_Factory_UnserializeService.php', true],
], [
    'Base64' => '?',
    'Iterator' => '?',
    'LocaleSwitcher' => '?',
    'ObjectBrickSetter' => '?',
    'PHPCode' => '?',
    'Published' => '?',
    'Splitter' => '?',
    'Unserialize' => '?',
]), new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'DefaultValue' => ['privates', 'pimcore.data_object.import.value.factory.default', 'getPimcore_DataObject_Import_Value_Factory_DefaultService.php', true],
], [
    'DefaultValue' => '?',
]));
