<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.authentication.provider.two_factor.admin' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/AuthenticationProviderInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/scheb/two-factor-bundle/Security/Authentication/Provider/TwoFactorAuthenticationProvider.php';
include_once \dirname(__DIR__, 4).'/vendor/scheb/two-factor-bundle/Security/TwoFactor/Backup/BackupCodeManagerInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/scheb/two-factor-bundle/Security/TwoFactor/Backup/NullBackupCodeManager.php';

return $this->privates['security.authentication.provider.two_factor.admin'] = new \Scheb\TwoFactorBundle\Security\Authentication\Provider\TwoFactorAuthenticationProvider('admin', ['auth_form_path' => '/admin/login/2fa', 'check_path' => '/admin/login/2fa-verify', 'default_target_path' => '/admin', 'always_use_default_target_path' => false, 'auth_code_parameter_name' => '_auth_code', 'trusted_parameter_name' => '_trusted', 'multi_factor' => false, 'success_handler' => NULL, 'failure_handler' => NULL, 'authentication_required_handler' => NULL, 'csrf_token_generator' => NULL, 'csrf_parameter' => '_csrf_token', 'csrf_token_id' => 'two_factor', 'provider' => NULL], ($this->privates['scheb_two_factor.provider_registry'] ?? $this->load('getSchebTwoFactor_ProviderRegistryService.php')), new \Scheb\TwoFactorBundle\Security\TwoFactor\Backup\NullBackupCodeManager());
