<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Maintenance\Tasks\TagsExpireTask' shared autowired service.

@trigger_error('The "Pimcore\\Maintenance\\Tasks\\TagsExpireTask" service is deprecated and will be removed in Pimcore 7', E_USER_DEPRECATED);

return new \Pimcore\Maintenance\Tasks\TagsExpireTask(($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()));
