<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Model\Notification\Service\UserService' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/models/Notification/Service/UserService.php';

return $this->privates['Pimcore\\Model\\Notification\\Service\\UserService'] = new \Pimcore\Model\Notification\Service\UserService();
