<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Templating\Helper\WebsiteConfig' shared autowired service.

@trigger_error('The "Pimcore\\Templating\\Helper\\WebsiteConfig" service is deprecated and will be removed in Pimcore 7', E_USER_DEPRECATED);

return $this->privates['Pimcore\\Templating\\Helper\\WebsiteConfig'] = new \Pimcore\Templating\Helper\WebsiteConfig(($this->services['Pimcore\\Http\\RequestHelper'] ?? $this->getRequestHelperService()));
